@tool
extends FlowNodeBase

# grid_size — Hierarchical generation (UE HiGen) Grid Size marker
#
# Every node downstream of this marker runs on the marker's grid level: once
# per cell of `cell_size` (a power of two) when the graph is generated by a
# FlowWorld3D. A node downstream of several markers takes the smallest size;
# nodes with no marker upstream run once, on the Unbounded level. Levels are
# computed at compile time from the graph topology (FlowCompiledGraph
# node_levels / level_plan), not from anything this node does at run time.
#
# At run time the node is a pure pass-through. Graphs that include it evaluate
# identically to graphs without it outside FlowWorld3D (FlowGraphNode3D,
# FlowNodeIO.evaluate, the editor preview).
#
# DEPRECATED side effect: it still writes the snapped cell size to
# ctx.variables[GridSizeNodeSettings.CTX_KEY] ("__grid_size__cell_size"), the
# annotation the pre-WP5 foundation used. Nothing reads it any more; read
# EvaluationContext.grid_size (or the grid_size @data attribute of Get
# Execution Bounds) instead.

const GridSizeSettings = preload("res://addons/flow_nodes_editor/nodes/grid_size_settings.gd")

func _init():
	meta_node = {
		"title"    : "Grid Size",
		"settings" : GridSizeSettings,
		"ins"      : [{ "label" : "In", "data_type" : FlowData.DataType.Invalid }],
		"outs"     : [{ "label" : "Out", "data_type" : FlowData.DataType.Invalid }],
		"tooltip"  : (
			"Hierarchical generation: the nodes downstream run once per cell of\n"
			+ "this power-of-two size when a FlowWorld3D generates the graph\n"
			+ "(the smallest size wins under several markers; nodes without a marker\n"
			+ "upstream run once, Unbounded). Data passes through unchanged."
		),
		"category" : "ControlFlow",
		"aliases"  : ["Grid Size", "HiGen", "Partition"],
	}

func getTitle() -> String:
	if settings and settings.label and not settings.label.strip_edges().is_empty():
		return "Grid Size: %s" % settings.label
	return "Grid Size"

func getExposedParams():
	return []

func widget_refresh(widget):
	widget.title = getTitle()

func execute(ctx: FlowData.EvaluationContext):
	# Pass data through unchanged.
	var in_data: FlowData.Data = get_optional_input(0)
	if in_data == null:
		in_data = FlowData.Data.new()

	# Annotate the evaluation context with the declared cell size.
	# Key: GridSizeNodeSettings.CTX_KEY = "__grid_size__cell_size"
	# Value: float — the snapped power-of-two cell size from settings.
	var cell_size: float = 1.0
	if settings:
		cell_size = settings.cell_size
	ctx.variables[GridSizeSettings.CTX_KEY] = cell_size

	set_output(0, in_data)
